//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Azki.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insurance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Insurance()
        {
            this.PaiedInsurances = new HashSet<PaiedInsurance>();
            this.PersonalInsurances = new HashSet<PersonalInsurance>();
            this.Reminders = new HashSet<Reminder>();
            this.WealthInsurances = new HashSet<WealthInsurance>();
        }
    
        public int InsuranceId { get; set; }
        public string OfferName { get; set; }
        public int ContractTime { get; set; }
        public long Price { get; set; }
        public int InsuranceCompanyId { get; set; }
        public Nullable<int> DiscountPercent { get; set; }
    
        public virtual InsuranceCompany InsuranceCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaiedInsurance> PaiedInsurances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonalInsurance> PersonalInsurances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reminder> Reminders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WealthInsurance> WealthInsurances { get; set; }
    }
}
