//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Azki.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaiedInsurance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaiedInsurance()
        {
            this.Places = new HashSet<Place>();
            this.SupplementaryHealthInsuranceUsers = new HashSet<SupplementaryHealthInsuranceUser>();
        }
    
        public int PaiedInsuranceId { get; set; }
        public int InsuranceType { get; set; }
        public int InsuranceId { get; set; }
        public int UserId { get; set; }
        public int Point { get; set; }
    
        public virtual Insurance Insurance { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Place> Places { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplementaryHealthInsuranceUser> SupplementaryHealthInsuranceUsers { get; set; }
    }
}
