//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Azki.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place
    {
        public int PlaceId { get; set; }
        public string Address { get; set; }
        public int PostalCode { get; set; }
        public int Roof { get; set; }
        public string Phone { get; set; }
        public int Plate { get; set; }
        public int Unit { get; set; }
        public int PaiedInsuranceId { get; set; }
    
        public virtual PaiedInsurance PaiedInsurance { get; set; }
    }
}
