//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Azki.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SicknessCoverageType
    {
        public int SicknessCoverageTypesId { get; set; }
        public string Title { get; set; }
    
        public virtual SicknessCoverage SicknessCoverage { get; set; }
    }
}
