//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Azki.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SicknessCoverageType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SicknessCoverageType()
        {
            this.SicknessCoverages = new HashSet<SicknessCoverage>();
        }
    
        public int SicknessCoverageTypesId { get; set; }
        public string Title { get; set; }
    
        public virtual SicknessCoverage SicknessCoverage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SicknessCoverage> SicknessCoverages { get; set; }
    }
}
