//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Azki.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplementaryHealthInsuranceUser
    {
        public int SupplementaryHealthInsuranceUserId { get; set; }
        public string AgeRange { get; set; }
        public string RelationshipWithSupervisor { get; set; }
        public int PaiedInsuranceId { get; set; }
    
        public virtual PaiedInsurance PaiedInsurance { get; set; }
    }
}
